[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
backend = "92TRmey1biFtJMR8oMCMd2oZQmfiAF5CR3zvTQPixLCp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/data/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
